package phoenix.wallpaper;

/**
 * The Android resource table (generated by aapt2 from android/app/src/main/res).
 * Referencing R.id.* / R.layout.* from Haxe keeps the settings screen wired up by
 * compile-time checked constants instead of string lookups.
 */
@:native("dev.phoenix.wallpaper.R")
extern class R {}
